image: registry.fedoraproject.org/fedora:latest

variables:
  GIT_DEPTH: '5'
  DEPENDENCIES: >-
    meson librsvg2 gtk4-devel glib2-devel gcc  glibc-devel

build:
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - echo meson awesomeness goes here

