#!/bin/sh
xcursorgen left_ptr_watch.in ../../../Adwaita/cursors/left_ptr_watch
xcursorgen hand1.in ../../../Adwaita/cursors/hand1
xcursorgen hand2.in ../../../Adwaita/cursors/hand2
xcursorgen left_ptr.in ../../../Adwaita/cursors/left_ptr
#xcursorgen center_ptr.in ../../../Adwaita/cursors/center_ptr
xcursorgen xterm.in ../../../Adwaita/cursors/xterm
xcursorgen crossed_circle.in ../../../Adwaita/cursors/crossed_circle
xcursorgen right_ptr.in ../../../Adwaita/cursors/right_ptr
xcursorgen copy.in ../../../Adwaita/cursors/copy
xcursorgen move.in ../../../Adwaita/cursors/move
xcursorgen pointer-move.in ../../../Adwaita/cursors/pointer-move
xcursorgen link.in ../../../Adwaita/cursors/link
xcursorgen circle.in ../../../Adwaita/cursors/circle
xcursorgen sb_h_double_arrow.in ../../../Adwaita/cursors/sb_h_double_arrow
xcursorgen sb_v_double_arrow.in ../../../Adwaita/cursors/sb_v_double_arrow
xcursorgen top_left_corner.in ../../../Adwaita/cursors/top_left_corner
xcursorgen top_right_corner.in ../../../Adwaita/cursors/top_right_corner
xcursorgen bottom_left_corner.in ../../../Adwaita/cursors/bottom_left_corner
xcursorgen bottom_right_corner.in ../../../Adwaita/cursors/bottom_right_corner
xcursorgen fd_double_arrow.in ../../../Adwaita/cursors/fd_double_arrow
xcursorgen bd_double_arrow.in ../../../Adwaita/cursors/bd_double_arrow
xcursorgen watch.in ../../../Adwaita/cursors/watch
xcursorgen sb_left_arrow.in ../../../Adwaita/cursors/sb_left_arrow
xcursorgen sb_right_arrow.in ../../../Adwaita/cursors/sb_right_arrow
xcursorgen sb_up_arrow.in ../../../Adwaita/cursors/sb_up_arrow
xcursorgen sb_down_arrow.in ../../../Adwaita/cursors/sb_down_arrow
#xcursorgen based_arrow_down.in ../../../Adwaita/cursors/based_arrow_down
#xcursorgen based_arrow_up.in ../../../Adwaita/cursors/based_arrow_up
xcursorgen bottom_side.in ../../../Adwaita/cursors/bottom_side
xcursorgen top_side.in ../../../Adwaita/cursors/top_side
xcursorgen left_side.in ../../../Adwaita/cursors/left_side
xcursorgen right_side.in ../../../Adwaita/cursors/right_side
xcursorgen grabbing.in ../../../Adwaita/cursors/grabbing
xcursorgen question_arrow.in ../../../Adwaita/cursors/question_arrow
xcursorgen top_tee.in ../../../Adwaita/cursors/top_tee
xcursorgen bottom_tee.in ../../../Adwaita/cursors/bottom_tee
xcursorgen left_tee.in ../../../Adwaita/cursors/left_tee
xcursorgen right_tee.in ../../../Adwaita/cursors/right_tee
xcursorgen ul_angle.in ../../../Adwaita/cursors/ul_angle
xcursorgen ll_angle.in ../../../Adwaita/cursors/ll_angle
xcursorgen ur_angle.in ../../../Adwaita/cursors/ur_angle
xcursorgen lr_angle.in ../../../Adwaita/cursors/lr_angle
xcursorgen X_cursor.in ../../../Adwaita/cursors/X_cursor
#xcursorgen crosshair.in ../../../Adwaita/cursors/crosshair
xcursorgen crosshair.in ../../../Adwaita/cursors/cell
xcursorgen cross.in ../../../Adwaita/cursors/cross
xcursorgen tcross.in ../../../Adwaita/cursors/tcross
xcursorgen dotbox.in ../../../Adwaita/cursors/dotbox
xcursorgen plus.in ../../../Adwaita/cursors/plus
xcursorgen pencil.in ../../../Adwaita/cursors/pencil
xcursorgen dnd-none.in ../../../Adwaita/cursors/dnd-none
xcursorgen dnd-copy.in ../../../Adwaita/cursors/dnd-copy
xcursorgen dnd-link.in ../../../Adwaita/cursors/dnd-link
xcursorgen dnd-move.in ../../../Adwaita/cursors/dnd-move
xcursorgen dnd-ask.in ../../../Adwaita/cursors/dnd-ask
xcursorgen dnd-no-drop.in ../../../Adwaita/cursors/dnd-no-drop
xcursorgen zoom-in.in ../../../Adwaita/cursors/zoom-in
xcursorgen zoom-out.in ../../../Adwaita/cursors/zoom-out
xcursorgen all-scroll.in ../../../Adwaita/cursors/all-scroll
xcursorgen vertical-text.in ../../../Adwaita/cursors/vertical-text
xcursorgen context-menu.in ../../../Adwaita/cursors/context-menu
